spring.application.name=ms-gerente
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5434/bantads
spring.datasource.username=bantads
spring.datasource.password=bantads
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=gerente
